version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/inventoryq
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: y@suk321

  db:
    image: your-image-name:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventoryq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y@suk321
